# Generated by Django 3.2.9 on 2021-11-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='currentDonation',
            field=models.IntegerField(default=70),
        ),
        migrations.AddField(
            model_name='post',
            name='goalDonation',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
